name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install requirements dependencies 
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install test dependencies 
      run: |
        pip install flake8 pylint black pytest pytest-cov

  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Find all Python files
      id: find_files
      run: |
        files=$(find . -name '*.py' ! -name '__init__.py')
        echo "files=$files" >> $GITHUB_ENV

    
    - name: Lint with flake8 to check Syntax Errors
      if: env.files != ''
      run: |
        flake8 ${{ env.files }} --count --select=E9,F7,F82 --show-source --statistics
        
    - name: Lint with pylint
      if: env.files != ''
      run: |
        pylint ${{ env.files }}

    - name: Check coding style
      if: env.files != ''
      run: |
        black ${{ env.files }} --check --diff 
    
    - name: Test with pytest and measure coverage
      run: |
        pytest --cov=lit_ecology_classifier
