name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


  linting:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install linting dependencies
    - name: Install linting dependencies
      run: |
        pip install flake8 pylint black

    # Linting steps
    - name: Lint with flake8
      run: |
        flake8 -v lit_ecology_classifier/**/*.py --count --select=E9,F7,F82 --show-source --statistics
        
    - name: Lint with pylint
      run: |
        pylint lit_ecology_classifier/**/*.py

    - name: Check coding style with Black
      run: |
        black lit_ecology_classifier/**/*.py --check --diff 

  unit_tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install testing dependencies
    - name: Install test dependencies
      run: |
        pip install pytest pytest-cov mock

    # Run unit tests with coverage
    - name: Run unit tests
      run: |
        pytest --cov=lit_ecology_classifier