name: Sync Docs Branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout docs branch
        run: git checkout docs

      - name: Sync main to docs
        run: |
          git merge main --no-edit --allow-unrelated-histories  || {
            echo "Merge conflicts detected, aborting.";
            git merge --abort;
            exit 1;
          }

      - name: Push changes
        run: git push origin docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

